AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: java8
    Tracing: Active
    MemorySize: 512
    Timeout: 60
    Environment:
      Variables:
        LEADERBOARD_TABLE_NAME: !Ref Leaderboard

Resources:
  TweetProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/retweet-leaderboard-1.0.0-SNAPSHOT.jar
      Handler: com.jlhood.retweetcounter.lambda.TweetProcessorHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Leaderboard

  GetLeaderboard:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/retweet-leaderboard-1.0.0-SNAPSHOT.jar
      Handler: com.jlhood.retweetcounter.lambda.GetLeaderboardHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Leaderboard
      Events:
        GetLeaderboardApi:
          Type: Api
          Properties:
            Path: /leaderboard
            Method: get

  Leaderboard:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
